# Generated by Django 2.2.6 on 2019-11-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=6, unique=True, verbose_name='社員番号')),
                ('is_attendance', models.BooleanField(verbose_name='出席？')),
                ('seat', models.IntegerField(blank=True, null=True, verbose_name='座席番号')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_no', models.IntegerField(verbose_name='空いている座席番号')),
            ],
        ),
    ]
